dchaley/deepcell-segmentation

notebooks/Benchmarking-Postprocess.ipynb
notebooks/Predict-Segments.ipynb
notebooks/imaging_helpers.py
notebooks/requirements.txt

Extend the postprocessing benchmarking notebook with snakeviz & speedscope profiling.  Use a variable to specify which mode; it then either opens a snakeviz tab or generates a speedscope.json file when postprocessing is complete.
Note that snakeviz's underlying profile is sampled so not all time is accounted for and sometimes the call stack looks off. Speedscope captures the time more precisely.
Use speedscope at: http://speedscope.app

Add snakeviz & speedscope profiling options

---

sample-data/deepcell/mesmer-sample-0/raw_output_image.npz
sample-data/deepcell/mesmer-sample-1/raw_output_image.npz
sample-data/deepcell/mesmer-sample-10/raw_output_image.npz
sample-data/deepcell/mesmer-sample-11/raw_output_image.npz
sample-data/deepcell/mesmer-sample-12/raw_output_image.npz
sample-data/deepcell/mesmer-sample-13/raw_output_image.npz
sample-data/deepcell/mesmer-sample-14/raw_output_image.npz
sample-data/deepcell/mesmer-sample-15/raw_output_image.npz
sample-data/deepcell/mesmer-sample-2/raw_output_image.npz
sample-data/deepcell/mesmer-sample-3/raw_output_image.npz
sample-data/deepcell/mesmer-sample-4/raw_output_image.npz
sample-data/deepcell/mesmer-sample-5/raw_output_image.npz
sample-data/deepcell/mesmer-sample-6/raw_output_image.npz
sample-data/deepcell/mesmer-sample-7/raw_output_image.npz
sample-data/deepcell/mesmer-sample-8/raw_output_image.npz
sample-data/deepcell/mesmer-sample-9/raw_output_image.npz

The actual raw output object is more complex than just a pixel array but we (so far?) only care about the pixel array. Extract it for convenience.
I did this by running this from the `benchmarking/h_maxima` directory:
```
for x in range(16):
marker_filename = "../../sample-data/deepcell/mesmer-sample-%s/raw_output_images.npz" % x
with np.load(marker_filename, allow_pickle=True) as loader:
marker_data = loader["output_images"]
marker_data = list(np.ndenumerate(marker_data))[0][1]
marker_data = marker_data['whole-cell'][0]
output_filename = "../../sample-data/deepcell/mesmer-sample-%s/raw_output_image.npz" % x
np.savez_compressed(output_filename, output_image=marker_data)
```

Extract single raw output image for convenience

---

benchmarking/h_maxima/README.md
benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/test_reconstruction.py
requirements.txt

Adds a test suite for our optimized code, lifted from scikit-image itself.
```
$ pytest test_reconstruction.py
============================ test session starts ============================
platform darwin -- Python 3.10.13, pytest-7.4.4, pluggy-1.3.0
rootdir: /Users/davidhaley/dev/deepcell-imaging/benchmarking/h_maxima
plugins: anyio-3.7.1, typeguard-4.0.0
collected 31 items
test_reconstruction.py ..xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                [100%]
======================= 2 passed, 29 xfailed in 0.80s =======================
```
Most of the tests are currently marked `xfail`, with links to follow-up issues (created in [this milestone](https://github.com/dchaley/deepcell-imaging/milestone/1)).
Closes #98

Add test suite for fast hybrid reconstruct

---

benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/fasthybridreconstruct.pyx
benchmarking/h_maxima/test_reconstruction.py

Closes #30 
Unfortunately this only fixes one test… this revealed some other issue, documented in #104 
```
======================================= test session starts ========================================
platform darwin -- Python 3.10.13, pytest-7.4.4, pluggy-1.3.0
rootdir: /Users/davidhaley/dev/deepcell-imaging/benchmarking/h_maxima
plugins: anyio-3.7.1, typeguard-4.0.0
collected 31 items
test_reconstruction.py ..xxxxxxxxxxxxxxxxxxxxxxxxx.xxx                                       [100%]
================================== 3 passed, 28 xfailed in 0.51s ===================================
```

Accept footprint parameter

---

benchmarking/deepcell-e2e/benchmark.ipynb

Pixels are more useful than the input size in bytes, as deepcell converts incoming data to 64-bit floats. But 15x10 is the same as 10x15, so just output the total number of pixels. Note that this is x*y, no matter how many channels are in the data.
Fixes #107

Add pixel count to benchmark data output

---

benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/test_reconstruction.py

Fixes #102 
This also fixes a couple of #104 failures but not all.

Fix test wrapper: the marker is modified in-place not mask

---

benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/fasthybridreconstruct.pyx
benchmarking/h_maxima/test_reconstruction.py

The current implementation outputs results as floats even if the input was ints. We don't want that for our optimizations, see also: https://github.com/dchaley/deepcell-imaging/issues/104
but we do need to maintain it in the existing API.
Current test results:
```
16 passed, 15 xfailed in 0.57s
```
Fixes #104

Maintain int-->float64 conversion

---

benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/fasthybridreconstruct.pyx
benchmarking/h_maxima/test_reconstruction.py

Implements the erosion method, which is the inverse of dilation (flip min/max).
This revealed the need for: #119 
To workaround the 1d test, I just converted it to a 1-row 2d array… 😓 
Furthermore: the tests exercise lots of types, the not-in-place version of this actually converts the image to float no matter what, and also treats the mask as float (b/c it assigns the mask into the float array).
There's gotta be a better way to handle this than to generate all permutations of mask/marker types. The cythonize command takes nearly a minute. Maybe that's just the deal for blazing performance. Or maybe we only enable this for matching marker & mask types? We have to verify anyhow that it's an array shape we support. (to pick which algorithm)
Fixes #99

Implement method=erosion

---

benchmarking/h_maxima/test_scikit_comparison.py

Generate random images & masks, then compare fast-hybrid reconstruct vs scikit's reconstruct.
This should never fail. Test runs can be made deterministic with a fixed seed per test. If it ever fails, well, good thing we found a problem!
Fixes #125

Add chaos-monkey comparison vs scikit

---

container/Dockerfile

This sets up a container that executes the steps in the benchmark setup notebook. It checks out the repo so in principle we could run the notebook however we haven't tried that yet.
Followed instructions here: https://cloud.google.com/deep-learning-containers/docs/derivative-container plus,
```
export IMAGE_NAME="${LOCATION}-docker.pkg.dev/${PROJECT}/${REPOSITORY_NAME}/benchmarking:v1"
export LOCATION="us-west1"
export REPOSITORY_NAME="deepcell-benchmarking"
```
I guess we change `v1` to `v2` on next push…?
Fixes #119

Create container with dependencies installed

---

benchmarking/deepcell-e2e/benchmark.py
container/Dockerfile
requirements.txt

Extract the interesting benchmark code from the notebook into a standalone benchmark script. Add an entry point command to the docker file to execute the script.
Because we're using custom jobs not notebooks, we changed the notebooks API to custom jobs. This means we need to pass the custom job ID to the benchmark as a parameter: --custom-job-id
This should be using the "args" parameter … we'll see.

Add container entry point into benchmark script

---

container/Dockerfile

This will be different each time the main branch changes. So, we can use the cached base image while rebuilding from main.
Surely there's a better way to have these huge base images cached?

Add github version.json to docker image to skip cache

---

benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/fasthybridreconstruct.pyx
benchmarking/h_maxima/test_reconstruction.py

Implement the footprint offset parameter, which allows centering the footprint on a point other than the center.
Along the way, clean up a few now-passing `xfail`s.
Fixes #100

Support reconstruct parameter: offset

---

benchmarking/deepcell-e2e/benchmark.py

For some reason not entirely clear to us, the aiplatform_v1 docs (which show how to call the ListCustomJobsRequest) don't seem to work. But, this approach works. It's different than the usual creating a client: instead the SDK is initialized globally(?).
Fixes #142

Use aiplatform not aiplatform_v1

---

benchmarking/h_maxima/benchmark_utils.py
benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/fasthybridreconstruct.pyx
benchmarking/h_maxima/test_opencv_comparison.py
benchmarking/h_maxima/test_reconstruction.py

This PR extends the OpenCV chaos testing by parameterizing the offset (or anchor point) in the footprint. In other words, randomize footprints, and also randomize which point is the center. This illuminates interesting edge cases around asymmetry. 🙃 
I identified bugs by parameterizing the comparison. I formalized those specific tests in `test_reconstruction.py`, deriving the expectations by hand in [this spreadsheet](https://docs.google.com/spreadsheets/d/15TntEi694OUy3ZjAdAdY2Ax6FTdCsCXiqGfpxpV7-iY/edit#gid=1552794151). I changed the code until the tests passed … and kept doing that until I stopped finding bugs.
One of the bugs was an interesting heisenbug, commit [c3b0028](https://github.com/dchaley/deepcell-imaging/commit/c3b00282ee48250f99746ee5363a45b6a4a5133b) fixed an …

Parameterize offset in OpenCV chaos testing

---

benchmarking/deepcell-e2e/benchmark.ipynb

Update the default batch size to 16 in our benchmarking as that's the one we use most commonly.
Importantly, add the `skip_postprocessing` parameter which creates a custom Mesmer application with a no-op post-processing step. Note that this makes the results unintelligible. It's reflected in the results with a different deepcell version: `_nopost`.
Fixes #172

Default batch size 16; parameter to skip postprocessing (results unintelligible)

---

benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/fasthybridreconstruct.pyx
benchmarking/h_maxima/test_reconstruction.py

Memory views are nice, but they hardcode the dimensions. That won't work for n-dimensional arrays…
This prepares #118 by refactoring the memory views into pointers. (We'll update the wrapper soon)
Along the way, aligns the mask dtype with the image dtype to dramatically reduce code size. (It's O(N) instead of O(N*N) combinations of types)
Fixes #175

Refactor memory views to pointers

---

benchmarking/h_maxima/.gitignore
benchmarking/h_maxima/fast_reconstruct_wrapper.py
benchmarking/h_maxima/fasthybridreconstruct.pyx
benchmarking/h_maxima/test_fast_hybrid.py
benchmarking/h_maxima/test_reconstruction.py

Refactors the fast-hybrid algorithm to support n-dimensional arrays.
See PR commits for step-by-step refactors from memory views & row/col indexing, into general C pointer indexing.
Fixes #118 
Fixes #171 
Commits from Mar 22, 2024 paired with Weihao

Generalize fast-hybrid to n-dimensional arrays

---

benchmarking/h_maxima/fasthybridreconstruct.pyx

Until this PR, we were iterating over the entire footprint, having zero'd out the before or after points as appropriate for the use. That was correct, but wasteful as we don't need to scan points in the inner loop that we're about to scan in the outer loop.
Along the way: I fixed the reverse scan to actually ... 🤦🏻  scan in reverse.
I also renamed & reorganized the code a bunch, aiming for clarity on top of performance. Also, removing some functions reduced the cythonize time (cython to C + compilation) by ~50%. 🎉 
_Highly Scientific Laptop Benchmark Results:_
Total time for OpenCV comparison: 6min 3s
Time to cythonize: ~14s
The cythonize time was previously ~26s, and total time was ... I think ... ~7min. (Should time this later?..., for science 🔬 )

Reduce number of inner loops & cythonize time

---

container/Dockerfile
container/batch.json

Previous compressed container size: 8.4 GB
New compressed container size: 3.2 GB
Fixes #192

Use smaller tf base image

---

batch/README.md
batch/run-job.py

Submitting a job by hand requires some busy-work: coming up with a job id and updating the output path to use that id.
This script automates this process by generating a job id, writing the appropriate json file, and submitting it to Batch via gcloud.
Fixes #219 

Add script to submit a batch job

---

container/Dockerfile
pyproject.toml
scripts/infer.py
scripts/postprocess.py
scripts/preprocess.py
scripts/visualize.py

This adds 4 independent entry point scripts:
- preprocess.py
- infer.py
- postprocess.py
- visualize.py
These implement the 3 phases plus an optional visualization step.
We added the pyproject to facilitate installing the module itself– we'll test shortly by building the container 😎
Paired with @WeihaoGe1009  
Fixes #222

Add entrypoint scripts + pyproject.toml + install self in container

---

scripts/infer.py
scripts/postprocess.py
scripts/preprocess.py

Output benchmarking data to an optional JSON file at the end of each step.
Also, round times to 2 decimal places.
Part of #238 but does not complete it. (We need to test, plus add a final step to gather all benchmarking data & write to BigQuery.)

Add benchmarking output to pre/infer/post steps

---

batch/run-multistep-job.py
deepcell_imaging/mesmer_app.py
deepcell_imaging/numpy_utils.py
run-sample.py
scripts/gather-benchmark.py
scripts/predict.py

Fixes issue #240. See issue for more context. TLDR: we need to provide the input size to postprocessing to resize back to original if necessary. We were passing in hard-coded 512x512. Now we fetch the numpy headers and use those to set the size.

Fetch input image size from remote file (don't hardcode)

---

deepcell_imaging/gcloud_storage_utils.py
scripts/pipeline.sh
scripts/postprocess.py
scripts/predict.py
scripts/preprocess.py
scripts/visualize.py

The Python API is ~80% slower than gcloud storage cp (which uses parallelization and other tricks).
This switches most of our I/O to gcloud storage cp. We didn't convert:
- model download. (Uses the cached_open library, which we control but didn't feel like doing yet)
- visualization. (Writes images, not numpy, need to generalize to byte streams or something)
Fixes #248.

Use gcloud storage cp instead of Python API

---

container/Dockerfile
deepcell_imaging/gcloud_storage_utils.py
scripts/pipeline.sh

It seems that pigz (multi-threaded/processed gzip) is order(s) of magnitude faster than numpy savez_compressed.
Support .gz remote links, and compress/decompress using pigz/unpigz as necessary.

Use pigz and add gcloud storage to container

---

.github/workflows/main.yml

Invoke cloud build in the GCP project, rather than build here.
That means we'll need a way to move the container from Google to Docker Hub. Previously, we'd have simply pushed the container we just built to both.

Switch from building on GitHub Actions to Cloud Build

---

.github/workflows/main.yml
container/Dockerfile
container/build-batch-container.yaml

Set up a build config that pushes the container to both private Artifact Registry & public Docker Hub.
Redirects the GitHub actions workflow to use this new config.
While we're here, remove graphviz from container dependencies– this should save on fonts & stuff, I think we got it from copy/pasta.

Push builds to GCP Artifact Registry and Docker Hub

---

benchmarking/deepcell-e2e/benchmark.py
scripts/postprocess.py

This adds flags to output the predictions as a TIFF file. If outputting as a TIFF, provides the additional option to squeeze the output (ie remove all axes of length 1).
See also #253 for ongoing discussion.

Output predictions tiff in benchmark script

---

benchmarking/deepcell-e2e/benchmark.py

The smart_open API seems to not support file seeking, which tifffile uses. (See also #253)
We already have gcloud_storage_utils which buffers to a local file before using the `gcloud` CLI to upload (it's a lot more performant). That means, it has access to normal file seeking.
And we get a performance boost for large prediction TIFFs, yay 😎

Use gcloud_storage_utils for writing TIFF to GCP

---

benchmarking/deepcell-e2e/benchmark.py
scripts/postprocess.py

The DeepCell code I copied provided the option to "np.squeeze" the output, aka remove axes of length one. Something like:
`(1, 512, 512, 1)`    (one 512x512 image w/ 1 channel value)
becomes
`(512, 512)` (512x512 pixel values)
But, turns out [we don't need it](https://github.com/dchaley/deepcell-imaging/issues/253#issuecomment-2206531897).
So ... let's get rid of it 👋🏻
We still need to resolve the question of batch dimension or not. We currently do not output the batch dimension. We output: 512x512x1

Remote output squeeze option

---

batch/run-multistep-job.py
deepcell_imaging/benchmark_utils.py
scripts/pipeline.sh
scripts/postprocess.py
scripts/predict.py
scripts/preprocess.py

We need to be able to specify the model path & hash, to customize where to pull the model from. This adds those to the multistep job wrapper, as well as to the individual predict.py step.
Also, fixes a bug in reporting the input file id.

Add model_path and model_hash arguments to run-multistep-job

---

batch/run-multistep-job.py
benchmarking/deepcell-e2e/benchmark.py
deepcell_imaging/mesmer_app.py
scripts/pipeline.sh
scripts/postprocess.py
scripts/visualize.py

This includes an API change: we now return the postprocessed data without the batch dimension. This normalizes it across the app (where we work on 1 image at a time).
Also add a tiff output to multi-step (todo: parameterize filename).
Paired with @WeihaoGe1009 @bnovotny 
Related to #253 (but not quite done yet: need to customize the tiff output name)

Output tiffs as int32 in benchmark + multistep

---

batch/run-multistep-job.py

Update the multi-step job to write the TIFF file using the input file basename as its own basename.
Example: input23.npz → input23.tiff
Paired with @WeihaoGe1009 @bnovotny 
Fixes #253

Multi-step job: write tiff using input file basename

---

batch/run-multistep-job.py
deepcell_imaging/mesmer_app.py
scripts/pipeline.sh
scripts/predict.py

The post [TensorFlow Performance: Loading Models](https://towardsdatascience.com/tensorflow-performance-loading-models-fb2d0dc340a3) revealed just how much the model format affects its load time. This graph is the punchline:
We loaded the SavedModel format and simply resaved it as `.keras`. To reload it, we needed to reference the DeepCell layer type `Location2D` in the model loader.
The results are astonishing! From local benchmarking:
```
Before:
Loaded model in 12.3 s
Ran prediction in 1.25 s; success: True
After:
Loaded model in 0.84 s
Ran prediction in 1.19 s; success: True
```
A reduction of ~11.5s, or ~90%. 🎉 
This PR also cleans up some model fetching we were doing before the mesmer-in-pieces app became a proper module. Oops 🙈   Sorry @bnovotny 
WIP for: #262 
Open work: test & …

Use keras format

---

batch/run-multistep-job.py
scripts/pipeline.sh

The .keras format didn't come out until 2.12 (maybe later). So, it was implicitly saving as HDF5. Whoops.
I renamed the file on storage, this follows up to adjust the default.
Follow up to #276

Use renamed h5 not .keras (it's actually hdf5)

---

deepcell_imaging/gcp_logging.py
deepcell_imaging/mesmer_app.py
requirements.txt
scripts/gather-benchmark.py
scripts/postprocess.py
scripts/predict.py
scripts/preprocess.py
scripts/visualize.py

GCP logging understands the JSON logstash format, not whatever Python loggers output normally.
This adds a helper function to configure a logger with a new handler which formats the log to JSON.
This should improve our logs in the GCP log viewer, for example it should no longer incorrectly identify logs as errors.
**Note**: we observed strange behavior locally: on our first run, it wrote to the classic (stdout) formatter AS WELL as the json formatter. It never did that again, and we're not sure if we changed anything. Well, it doesn't do it anymore… but let's keep an eye out.
Fixes #220

Use JSON logging

---

deepcell_imaging/gcp_logging.py
scripts/gather-benchmark.py
scripts/postprocess.py
scripts/predict.py
scripts/preprocess.py
scripts/visualize.py

We saw duplicate log entries after we added the GCP handler: https://github.com/dchaley/deepcell-imaging/issues/279
We saw this once locally, but it went away; then it came back on cloud. This should "just fix" it.
This PR removes any default handlers from the root logger, and moves the GCP JSON formatter to the root as well (so that ALL loggers use it, not just our own).
Fixes #279.

Move GCP JSON formatter to root & remove other handlers

---

batch/example-config.json
batch/run-multistep-job.py
batch/run-qupath-job.py
deepcell_imaging/gcp_batch_jobs.py

This adds a --configuration flag to the job launchers, which refers to a JSON file that we merge into the base job parameters. The config *overrides* whatever the base job says.
Use this to specify a network, subnetwork, service account, etc.
Fixes #284

Get batch configuration fields from config file

---

batch/run-multistep-job.py
batch/run-qupath-job.py
deepcell_imaging/gcp_batch_jobs.py

We used to take the parameter but ... do nothing with it. 🤦🏻  This now passes it through properly.
Fixes #285

Pass compartment from runner to job json

---

benchmarking/20240722_smart_open_and_gs_fastcopy_benchmark.py

Adds a new benchmark for gs-fastcopy without the smart_open calls
Fixes #295

Add new benchmark with just gs_fastcopy

---

batch/run-multistep-job.py
batch/run-qupath-job.py
deepcell_imaging/gcp_batch_jobs.py
requirements.txt
scripts/gather-benchmark.py
scripts/pipeline.sh
scripts/postprocess.py
scripts/predict.py
scripts/preprocess.py
scripts/visualize.py

To support running on multiple inputs in one job, we need the task runners to understand $BATCH_TASK_INDEX: they use this to determine which of a list of inputs they're operating upon.
The bulk of the work is updating how the scripts take their command-line arguments: either a file, or, individual arguments as usual.
This introduces pydantic as a way to define the script parameters aka API. The idea is to reduce duplicated data like which parameters are required or what their defaults are. (Some more work needed here like generating the arguments from the type def, and moving the help text into the type too.)
This adds a helper to fetch the task list.
Relates to #292
Most of this paired with @WeihaoGe1009 
**REVIEW NOTE**: consider ignoring whitespace to see that the args are (mostly) …

Accept indexed task args

---

batch/run-qupath-job.py
deepcell_imaging/gcp_batch_jobs/multitask.py
pyproject.toml

This updates the run-qupath-job batch job launcher to create a list of tasks, one for each pair of TIFF+npz files.
The tasks then run DeepCell and put the prediction mask TIFFs into the SEGMASK directory. This makes the dataset ready for QuPath processing.
Fixes #292.

Update QuPath job to run multiple predictions

---

container/Dockerfile
scripts/launch-qupath-measurement.py
src/deepcell_imaging/gcp_batch_jobs/multitask.py
src/deepcell_imaging/gcp_batch_jobs/qupath_measurements.py
src/deepcell_imaging/gcp_batch_jobs/types.py

This script enqueues a Batch job to run QuPath measurements. It's intended to be the final step in a pipeline generating
(1) segmentation from DeepCell and
(2) quantitative measurement reports from QuPath.
Fixes #311
Example reports output:

Add script to enqueue QuPath job

---

src/deepcell_imaging/utils/cmdline.py

Third time is the charm? Some steps don't need the env config: so the argument shouldn't be required.

Make command line parameter optional

---

scripts/segment-and-measure.py
src/deepcell_imaging/gcp_batch_jobs/__init__.py
src/deepcell_imaging/gcp_batch_jobs/segment.py

The segmentation job uses local storage to download the input image and for intermediate storage. The default (30GB) isn't enough for larger images. This increases the boot disk size based on the input size.
Unfortunately, although we see the added space in the job json, it doesn't seem to be reflected in the GCE instance.

Add segmentation boot disk based on image size

---

src/deepcell_imaging/gcp_batch_jobs/__init__.py
src/deepcell_imaging/gcp_batch_jobs/segment.py

This solves the 1st half of #305: it adds the attached disk for the segmentation job.
We still need this for the qupath measurement job.

Replace boot disk with attached volume

---

scripts/segment-and-measure.py
src/deepcell_imaging/gcp_batch_jobs/types.py

Add an optional parameter to the environment configuration, specifying where to upload benchmarking data. If blank or unspecified, just don't upload any benchmarking.
Fixes #331 

Add BQ benchmarking table ID to environment config

---

scripts/segment.py
src/deepcell_imaging/utils/cmdline.py

This adds a job to just segment a dataset's images, without enqueuing the QuPath portion. Along the way we extract shared code between the two scripts (segment, and segment-and-measure).
Fixes #327

Add segmentation-only job

---

README.md
scripts/launch-qupath-measurement.py
scripts/segment-and-measure.py
src/deepcell_imaging/gcp_batch_jobs/__init__.py
src/deepcell_imaging/gcp_batch_jobs/quantify.py
src/deepcell_imaging/gcp_batch_jobs/segment.py
src/deepcell_imaging/gcp_batch_jobs/types.py

This allows users to set the networking & service account in the environment config. This is required in our target production environment.
Fixes #337 

Set networking & service account in env config

---

scripts/preprocess.py
src/deepcell_imaging/gcp_batch_jobs/segment.py
src/deepcell_imaging/gcp_batch_jobs/types.py
tests/deepcell_imaging/gcp_batch_jobs/quantify_test.py
tests/deepcell_imaging/gcp_batch_jobs/segment_test.py

Require passing in the image name. Previously, we guessed it from the filename using the directory containing the npz file. This is incorrect for QuPath project structures where the filename itself is the image name. Now, the job submission script has to decide what to call each image.
Also fix unit tests– we had forgotten to update them after adding the disks 😅
Fixes #330 

Use image name as benchmarking input id

---

container/build-batch-container.yaml

This builds the container using the previously built container as a cache.
But because we add the repository early in the process, we'll reinstall the requirements even if they didn't change, which is undesirable.

Add basic cache from previously built container

---

container/Dockerfile

This helps us cache the python requirements, which don't change that often. If the requirements.txt file is unchanged, Docker should reuse the previously built container layer. On the other hand if requirements.txt changes then it will reinstall dependencies from scratch.

Install python requirements outside full checkout

---

.github/workflows/main.yml
README.md
container/build-batch-container.yaml
container/push-dockerhub-container.yaml

The target environment shouldn't push to Docker Hub. Add condition to Docker Hub push, and do it separately.
This does mean the 2nd build needs to re-pull the container in order to add the tag and push it to Docker Hub. Oh, well…

Separate DockerHub push from main build

---

.envrc.template
.gcloudignore
.gitignore
container/Dockerfile
container/build-batch-container.yaml
container/cloud-build.sh

The target environment doesn't have access to GitHub so we need to get the code via source upload.
Change the Dockerfile to copy in files rather than check out the repo.
Also add a helper script to launch the Cloud Build job.

Build container from local files w/ helper script

---

scripts/enqueue-qupath-measurement.py
scripts/segment-and-measure.py
scripts/segment.py
src/deepcell_imaging/gcp_batch_jobs/__init__.py
src/deepcell_imaging/gcp_batch_jobs/quantify.py
src/deepcell_imaging/gcp_batch_jobs/segment.py
src/deepcell_imaging/gcp_batch_jobs/types.py
src/deepcell_imaging/utils/cmdline.py
tests/deepcell_imaging/gcp_batch_jobs/quantify_test.py
tests/deepcell_imaging/utils/cmdline_test.py

The compute allocation for jobs needs to change with input size.
For now, let the user control the compute config with command-line arguments.
Eventually, we may get smarter about sizing the machine based on pixels etc…
Fixes #371

Accept compute config parameters

---

src/deepcell_imaging/utils/storage.py
tests/deepcell_imaging/utils/storage_test.py

This can happen for blobs that were created as folders, for example if you create the blob gs://some/path/ then it counts as a blob.
Fixes #369

Filter out blobs with empty basenames

---

src/deepcell_imaging/gcp_batch_jobs/quantify.py
tests/deepcell_imaging/gcp_batch_jobs/quantify_test.py

This makes Java actually honor the TMPDIR; it doesn't look at the environment variable.
Fixes #382

Pass TMPDIR as java property for QuPath

---

requirements-mac-arm64.txt
requirements.txt
scripts/predictions-to-geojson.py
src/deepcell_imaging/gcp_batch_jobs/types.py

This script converts a prediction TIFF file into GeoJSON files. The reason is that ImageJ doesn't support TIFFs with more than ~2B pixels (32bit indexing), so we need an alternate method to detect the segmented regions.
Fixes #386

Export GeoJSON files

---

scripts/predictions-to-geojson.py
src/deepcell_imaging/gcp_batch_jobs/types.py

To integrate into the pipeline we need to process both prediction types: whole-cell and nucleus (we always run both).
Fixes #390

Output both whole-cell & nucleus geojson

---

scripts/predictions-to-geojson.py
src/deepcell_imaging/gcp_batch_jobs/segment.py

Fixes #397 
A JSONL file serializes a JSON array with an entry per line, rather than a comma-separated list. This lets applications process the file much more efficiently: handling a line aka entry one at a time vs having to load everything into memory.

Output shapes as jsonl

---

container/Dockerfile

The rebuild on TF2.17 fixed the TF issues, but, we're now using an older 22.04 with OS issues.
This PR runs `dist-upgrade` to update OS packages. (We may need to soften to `upgrade` as `dist-upgrade` can be more aggressive)

Add dist-upgrade to OS packages
