notebooks/Extract-Sample-Channels.ipynb, sample-data/deepcell/README.md, sample-data/deepcell/mesmer-sample-0/input_channels.npz, sample-data/deepcell/mesmer-sample-1/input_channels.npz, sample-data/deepcell/mesmer-sample-10/input_channels.npz, sample-data/deepcell/mesmer-sample-11/input_channels.npz, sample-data/deepcell/mesmer-sample-12/input_channels.npz, sample-data/deepcell/mesmer-sample-13/input_channels.npz, sample-data/deepcell/mesmer-sample-14/input_channels.npz, sample-data/deepcell/mesmer-sample-15/input_channels.npz, sample-data/deepcell/mesmer-sample-2/input_channels.npz, sample-data/deepcell/mesmer-sample-3/input_channels.npz, sample-data/deepcell/mesmer-sample-4/input_channels.npz, sample-data/deepcell/mesmer-sample-5/input_channels.npz, sample-data/deepcell/mesmer-sample-6/input_channels.npz, sample-data/deepcell/mesmer-sample-7/input_channels.npz, sample-data/deepcell/mesmer-sample-8/input_channels.npz, sample-data/deepcell/mesmer-sample-9/input_channels.npz
Extract DeepCell's mesmer sample data with a notebook, and commit to the repo.
=> Add notebook to extract DeepCell mesmer sample data

benchmarking/h_maxima/fasthybridreconstruct.pyx
Getting ready to circulate & publish this more– adding documentation!
=> Add documentation & clarify naming for fast-hybrid reconstruction

sample-data/deepcell/README.md
Solves some of: https://github.com/dchaley/deepcell-imaging/issues/25
Leaves some TODOs.
=> Improve DeepCell/mesmer sample documentation

sample-data/10x-genomics/README.md, sample-data/10x-genomics/preview-human-breast-20221103-418mb/selectedregion_deepcell_input_image.png, sample-data/10x-genomics/preview-human-breast-20221103-418mb/selectedregion_deepcell_input_image_small.png, sample-data/10x-genomics/preview-human-breast-20221103-418mb/selectedregion_deepcell_predicted_segments.png, sample-data/10x-genomics/preview-human-breast-20221103-418mb/selectedregion_deepcell_predicted_segments_small.png, sample-data/10x-genomics/preview-human-breast-20221103-418mb/selectedregion_input_image_channel_HER2.png, sample-data/10x-genomics/preview-human-breast-20221103-418mb/selectedregion_input_image_channel_HER2_small.png
Add the 10x Genomics sample preview-human-breast-20221103-418mb:
https://www.10xgenomics.com/products/xenium-in-situ/preview-dataset-human-breast
Adds preview files to the repo, and README links to cloud storage.
Also adds TODO section for next sample: human-prostate-cancer-20210727-725mb
=> Add sample: preview-human-breast-20221103-418mb

benchmarking/deepcell-e2e/benchmark.ipynb
=> Use correct memory unit factor across mac/linux

benchmarking/deepcell-e2e/benchmark.ipynb
=> Add batch_size parameter

benchmarking/h_maxima/fasthybridreconstruct.pyx, benchmarking/h_maxima/test_reconstruction.py
Closes #101 
Quick one here– doesn't fix any issues 😅 🔜
=> Support uint8 dtype

benchmarking/h_maxima/test_scikit_comparison.py
=> Parameterize random seed in scikit comparison test

benchmarking/deepcell-e2e/benchmark.py, container/Dockerfile, container/README.md
Fixes some bugs:
- we don't have the job id until we create it! So we need to filter on the display name we choose.
- fix the entry point path in the docker container.
=> Create custom job

benchmarking/deepcell-e2e/benchmark.py
=> Use project name in table id

benchmarking/deepcell-e2e/benchmark.py
=> Add debugging: gcloud auth list

benchmarking/deepcell-e2e/benchmark.py
=> Attempt to fetch & display project id from metadata

container/README.md
=> Fix command to launch custom job

benchmarking/h_maxima/benchmark_utils.py, benchmarking/h_maxima/test_opencv_comparison.py
Fixes #128
The footprint was parameterized in other work, here it just extends to row/col not just a square size.
=> Parameterize footprint rows/cols

notebooks/Generate-Classification-Report.ipynb
=> Notebook to generate classification report

benchmarking/deepcell-e2e/benchmark.py
=> Add method to call metadata server

benchmarking/deepcell-e2e/benchmark.py
=> Output machine config in results

benchmarking/deepcell-e2e/benchmark.py
=> Add gcp_service to csv upload

benchmarking/deepcell-e2e/benchmark.py
=> Extract the machine type portion from the qualified string

benchmarking/deepcell-e2e/benchmark.py, requirements.txt
=> Add bq upload retries using tenacity

benchmarking/h_maxima/fasthybridreconstruct.pyx, benchmarking/h_maxima/test_scikit_comparison.py
The main fix in this PR is hand-rolling the type casts from the first commit. Previously it was going through the python type system meaning that there aren't 2 kinds of ints, floats, etc.
Then I got sidetracked into performance tuning b/c some of the numbers surprised me. I need to clean this up, but am going to checkpoint now rather than make 2 prs etc.
=> Fixing type inference & n dimensions

benchmarking/deepcell-e2e/benchmark.py
=> Only retry BQ upload on exceeding rate limits

benchmarking/deepcell-e2e/benchmark.py
=> Update to results_batch bigquery table

benchmarking/deepcell-e2e/benchmark.py
We used to set these in the notebook directly.
Now, set them as command-line parameters.
Fixes #202
=> Add command-line parameters to benchmark script

container/batch.json
=> Add 3 retries for spot preemption exit code

benchmarking/deepcell-e2e/benchmark.py
=> Output to a base path, not individual files

container/README.md, container/batch.json
=> Add readme to run jobs & sample batch json to new parameters

container/cloud-build.sh
=> Add script to build new image

README.md, requirements-mac-arm64.txt
The solution is a bit awkward (needing to install without deps) but ... it works.
=> Requirements and instructions for running on Mac silicon

requirements-mac-arm64.txt
=> Add dependencies we need installed

deepcell_imaging/mesmer_app.py, run-sample.py
The mesmer app in DeepCell is a stateful object that runs all 3 passes: preprocess, infer, postprocess.
We need to run them independently, without shared state.
This PR extracts each phase to a stateless (aka "functional") interface, receiving all information it needs as parameters rather than depending on an object's state.
=> Extract mesmer app predict phases

container/gce-driver-install-startup-script.sh, scripts/gce-benchmark.sh
Just saving our progress. It launched a container, at least!
Fixes #242 
=> WIP scripts to run on GCE directly. NOTE: UNTESTED!

deepcell_imaging/benchmark_utils.py, scripts/gather-benchmark.py, scripts/postprocess.py, scripts/preprocess.py
We were missing a few fields from the benchmarking steps, so we added those. We also added the 4th script to gather the benchmarking data & send to BigQuery.
=> Add benchmark gather script + missing benchmark fields

batch/run-job.py
Paired with @lynnlangit 
Fixes #250
=> Parameterize run-job model_path

batch/run-multistep-job.py, deepcell_imaging/gcloud_storage_utils.py, scripts/postprocess.py, scripts/predict.py, scripts/preprocess.py
Converts the specialized numpy saver into a more idiomatic stream writer.
=> Improve gcloud storage writes

deepcell_imaging/gcloud_storage_utils.py, scripts/postprocess.py, scripts/predict.py, scripts/preprocess.py, scripts/visualize.py
=> Convert gcloud storage fetch_file to idiomatic reader

batch/run-multistep-job.py
=> Add bigquery table name param. Empty to disable.

batch/run-multistep-job.py, scripts/gather-benchmark.py
=> Skip gather-benchmark when table is empty

batch/run-job.py, batch/run-multistep-job.py
=> Use container tag batch not gce

batch/run-multistep-job.py, batch/run-qupath-job.py, deepcell_imaging/gcp_batch_jobs.py
This implements a batch job wrapper that sets up paths following the qupath conventions in #281.
=> Add qupath runner

benchmarking/gs_fastcopy_benchmark.py
Collecting results in: [spreadsheet](https://docs.google.com/spreadsheets/d/1PWR2GBuTRSJVn7IW3tjm964V_aMxnFRh1RNUcYD04po/edit?gid=0#gid=0).
=> Add benchmarking script: smart_open / gs_fastcopy

deepcell_imaging/notifications.py, requirements.txt
This is part of #283 but does not complete it.
See the comment: we aren't yet sure how this will integrate into which pipeline, so we aren't filling in the blanks. We did however verify that this works!
=> Add WIP template for sending Teams notifications

scripts/gather-benchmark.py
This makes sure each `load_table_from_file` uses a fresh IO object. See #303 for bug I think is caused by recycling the IO objects across retries.
Fixes #303
=> Create fresh StringIO on each BQ upload

scripts/pipeline.sh, src/deepcell_imaging/gcp_batch_jobs/types.py
=> Remove optionals; update pipeline.sh to have benchmarks

scripts/gather-benchmark.py, scripts/launch-qupath-measurement.py, scripts/postprocess.py, scripts/predict.py, scripts/preprocess.py, scripts/segment-and-measure.py, scripts/visualize.py, src/deepcell_imaging/gcp_batch_jobs/quantify.py, src/deepcell_imaging/utils/cmdline.py, tests/deepcell_imaging/utils/cmdline_test.py
This adds a config URI parameter, which jobs use to fetch a config json file from cloud storage.
This json specifies environment config, such as, the container image URLs to use, which region to run in, and future stuff we'll probably need!
Related to #314 
=> Load config from file

src/deepcell_imaging/benchmark_utils.py
=> Detect name-resolution errors & be quiet!

src/deepcell_imaging/gcp_batch_jobs/quantify.py, src/deepcell_imaging/gcp_batch_jobs/segment.py
See this issue for context: https://github.com/dchaley/qupath-project-initializer/issues/40
While we figure out the appropriate sizing, let's over-size for now (it's quite cheap).
=> Set QuPath disk to 500GB

README.md, benchmarking/bigquery_benchmarking_schema.json
This makes it easier for people to create a BQ table for benchmarking results.
Fixes #334
=> Add benchmarking BQ schema file + update readme

benchmarking/bigquery_benchmarking_schema.json, scripts/preprocess.py
=> Rename pixels_m in BigQuery upload + schema

README.md
=> Add git-lfs instructions

README.md, batch/run-job.py, batch/run-qupath-job.py, container/build-batch-container.yaml
=> Tag container as latest not batch

src/deepcell_imaging/image_processing/fast_hybrid.py
Add a trivial but useful comment, just to force a build.
We should see the container build time drop from ~13min to ?min, the slow part we're skipping is the python requirements.
=> Add comment to test container build

scripts/pipeline.sh, src/deepcell_imaging/mesmer_app.py
This replaces the deep_watershed's usage of h_maxima with our h_maxima, which in particular uses the fast-hybrid Cython version instead of scikit-image's version.
Relates to #350 , maybe fixes if this works :)
=> Use custom h_maxima

sample3_raw_predicted_maxima.npz, scripts/gather-benchmark.py, src/deepcell_imaging/mesmer_app.py
Some small changes while debugging h_maxima performance after integration into our code.
=> Debug hmaxima performance

src/deepcell_imaging/mesmer_app.py
Previously we were constructing "region properties" objects, even though we were barely using them. This incurred a very large number of albeit very small allocations & function calls but it added up.
This improves performance by:
- 260k pixel image: 202ms --> 170ms, 32ms 16%
BEFORE:
AFTER:
- 140M pixel image: 15.6s --> 11.7s, 3.9s or 25%
just for fill-holes, not the overall which was 113s --> 111s   (recall that these profilings are imprecise using cProfile)
BEFORE: (just for fill_holes)
AFTER: (just for fill_holes)
Fixes #357
=> Skip regionprops construction

.github/workflows/main.yml, README.md, container/build-batch-container.yaml
This parameterizes the Cloud Build configuration and, hopefully, the GitHub action to trigger it.
Relates to #360
=> Parameterize build

.github/workflows/main.yml
Fixes #362 which was supposed to fix #361 😩
=> Add leading underscore to variable name

scripts/enqueue-qupath-measurement.py, src/deepcell_imaging/gcp_batch_jobs/quantify.py, src/deepcell_imaging/utils/cmdline.py, tests/deepcell_imaging/gcp_batch_jobs/quantify_test.py, tests/deepcell_imaging/utils/cmdline_test.py
=> Allow empty accelerator in compute config

scripts/segment.py
=> Use service account + networking settings

setup.py, src/deepcell_imaging/gcp_batch_jobs/segment.py, src/deepcell_imaging/gcp_batch_jobs/types.py
Convert the numpy output into geojson shapes for predicted cells & nuclei.
Fixes #393
=> Integrate geo json into pipeline

scripts/postprocess.py
=> Fix prediction loading

src/deepcell_imaging/gcp_batch_jobs/segment.py
=> Fix phase name to match script name

container/Dockerfile
Fixes #401 (probably)
Need to test build post-merge
=> Update container base to TF 2.17 on Ubuntu22.04

container/Dockerfile
=> Add missing &&, sigh
